# Generated by Django 4.2.6 on 2023-11-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'Message'},
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='user2',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='user1',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='date_created',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='uuid',
        ),
        migrations.AddField(
            model_name='chat',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
