# Generated by Django 4.2.6 on 2023-11-01 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(max_length=2)),
                ('minutes', models.CharField(max_length=2)),
                ('period', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('source_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('source_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('passengers', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=20)),
                ('landmark', models.CharField(max_length=100)),
                ('ride_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishride.timedata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
