# Generated by Django 4.2.6 on 2023-11-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishride', '0002_reuquestride'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuquestride',
            name='passenger_count',
            field=models.IntegerField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
