# Generated by Django 4.2.6 on 2023-11-14 14:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publishride', '0004_ridechat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ride_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='publishride.reuquestride')),
            ],
        ),
    ]
