# Generated by Django 4.2.6 on 2023-11-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishride', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuquestride',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10),
        ),
    ]
