# Generated by Django 4.2.6 on 2023-11-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishride', '0009_alter_timedata_hours_alter_timedata_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='landmark',
        ),
    ]
