# Generated by Django 4.2.6 on 2023-11-27 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publishride', '0010_remove_ride_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuquestride',
            name='request_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
