# Generated by Django 4.2.6 on 2023-11-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishride', '0011_reuquestride_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.BooleanField(default=True),
        ),
    ]
