# Generated by Django 4.2.6 on 2023-10-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
