# Generated by Django 4.2.6 on 2023-10-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_otp_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_resend_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resend_count',
            field=models.IntegerField(default=0),
        ),
    ]
